  $(document).ready(function(){
    $("#move").click(function(){
        $("#one").slideDown();
    })
  })
  $(document).ready(function(){
    $("#hollas").click(function(){
      alert("You have Reached The Maximum Removed");
    })
  })
  $(document).ready(function(){
    $("#a").click(function(){
        $("#two").slideDown();
    })
  })
  $(document).ready(function(){
    $("#b").click(function(){
        $("#one").slideUp();
    })
  })
  $(document).ready(function(){
    $("#c").click(function(){
        $("#three").slideDown();
    })
  })
  $(document).ready(function(){
    $("#d").click(function(){
        $("#two").slideUp();
    })
  })
  $(document).ready(function(){
    $("#e").click(function(){
        $("#four").slideDown();
    })
  })
  $(document).ready(function(){
    $("#f").click(function(){
        $("#three").slideUp();
    })
  })
  $(document).ready(function(){
    $("#g").click(function(){
        $("#five").slideDown();
    })
  })
  $(document).ready(function(){
    $("#h").click(function(){
        $("#four").slideUp();
    })
  })
  $(document).ready(function(){
    $("#i").click(function(){
        $("#six").slideDown();
    })
  })
  $(document).ready(function(){
    $("#j").click(function(){
        $("#five").slideUp();
    })
  })
  $(document).ready(function(){
    $("#k").click(function(){
        $("#seven").slideDown();
    })
  })
  $(document).ready(function(){
    $("#l").click(function(){
        $("#six").slideUp();
    })
  })
  $(document).ready(function(){
    $("#m").click(function(){
        $("#eight").slideDown();
    })
  })
  $(document).ready(function(){
    $("#n").click(function(){
        $("#seven").slideUp();
    })
  })
  $(document).ready(function(){
    $("#o").click(function(){
        $("#nine").slideDown();
    })
  })
  $(document).ready(function(){
    $("#p").click(function(){
        $("#eight").slideUp();
    })
  })
  $(document).ready(function(){
    $("#q").click(function(){
        $("#ten").slideDown();
    })
  })
  $(document).ready(function(){
    $("#r").click(function(){
        $("#nine").slideUp();
    })
  })
  $(document).ready(function(){
    $("#s").click(function(){
        $("#eleven").slideDown();
    })
  })
  $(document).ready(function(){
    $("#t").click(function(){
        $("#ten").slideUp();
    })
  })
  $(document).ready(function(){
    $("#u").click(function(){
        alert("You have Reached The Maximum Allowed");
    })
  })
  $(document).ready(function(){
    $("#v").click(function(){
        $("#eleven").slideUp();
    })
  })